runtime: python27
api_version: 1
threadsafe: yes

# [START mail_service]
inbound_services:
- mail

handlers:

# [START handle_incoming_email]
- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
# [END handle_incoming_email]
- url: /
  static_files: index.html
  upload: index.html

env_variables:
    GCLOUD_PROJECT: img-recognition
    CLOUD_STORAGE_BUCKET: detection-images
